# Generated by Django 4.1.6 on 2023-02-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0004_alter_contacto_id_titulo_hist_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='a_materno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
