# Generated by Django 4.1.6 on 2023-02-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0005_alter_contacto_a_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='id_usuario_ingreso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hist_contacto',
            name='id_usuario_ingreso',
            field=models.IntegerField(),
        ),
    ]
