# Generated by Django 4.1.6 on 2023-02-10 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0006_alter_contacto_id_usuario_ingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Cargo',
            fields=[
                ('id_cargo', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tx_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Organismo',
            fields=[
                ('id_organismo', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tx_organismo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Tipo_Empleado',
            fields=[
                ('id_tipo_empleado', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tx_empleado', models.CharField(max_length=25)),
                ('id_padre_empleado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Titulo',
            fields=[
                ('id_titulo', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tx_titulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Unidad',
            fields=[
                ('id_unidad', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tx_unidad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('tx_usuario', models.CharField(max_length=20)),
                ('fh_ingreso', models.DateTimeField()),
                ('fh_baja', models.DateTimeField(blank=True, null=True)),
                ('id_tipo_usuario', models.BooleanField(default=2, verbose_name='1=Administrador, 2=Operador')),
            ],
        ),
        migrations.RenameField(
            model_name='hist_contacto',
            old_name='id_oficina',
            new_name='id_organismo',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='id_empleado',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='id_oficina',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_organismo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directoryapp.cat_organismo'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='id_tipo_empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='directoryapp.cat_tipo_empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directoryapp.cat_cargo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directoryapp.cat_titulo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directoryapp.cat_unidad'),
        ),
    ]
