# Generated by Django 4.1.6 on 2023-02-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0008_usuario_tx_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hist_contacto',
            name='id_usuario_ingreso',
            field=models.IntegerField(),
        ),
    ]
